version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: yubo_test/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - tensorflow_serving
    environment:
      - TENSORFLOW_SERVING_URL=${SERVING_URL}

  tensorflow_serving:
    build:
      context: Python_Engineer
    ports:
      - "8501:8501"

